apiVersion: v1
kind: Service
metadata:
  name: tavola-backend-service
spec:
  selector:
    app: tavola-backend
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: uploads
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer # ou NodePort, dependendo do seu ambiente